#!/bin/bash

#What u want to back up
Source=$""

#Where to back it up
Backup=$""

#sets DAY to Day of the week
DAY=$(date +%a)

#Gets data of last full back up
cat $Backup/Date.txt | while read Date; do

#if File exsits then deleat it
if [ -e $Backup/incr/$DAY ] ; then
  rm -fr $Backup/incr/$DAY
fi

#rsync differential daily backup
rsync -a --delete --quiet --inplace --backup --backup-dir=$Backup/incr/$DAY $Source $Backup/$Date/
done
