#!/bin/bash

#sets the date
Date=$(date +%F)

#rsunt selected files
rsync -a --delete --quiet $1 $2/$Date

#Creats most resent backup date file
echo "$Date" > "$2/Date.txt"

#cuts the end off $source
End=$(echo "$1" | awk -F/ '{print $NF}')

#Checks if Backup is sucsesful
diff -r "$1" "$2/$Date/$End"

#Notifation
if [[ $(echo $?) -eq 0 ]]; then
  message="Success"
else
  message="@everyone Fail"
fi

## format to parse to curl
## echo Sending message: $message
msg_content=\"$message\"

## discord webhook
url='https://discordapp.com/api/webhooks/825851796722417744/CNzrwOouexcnNnADMABSfJ8GjnEgs1YnwUG9SBWVkCxlRESpCvrTSycn0xX1u8RKk2I7'
curl -H "Content-Type: application/json" -X POST -d "{\"content\": $msg_content}" $url
