#!/bin/bash

#What u want to back up
Source="Sourd dir"

#Where to back it up
Backup="Bacup dir"

#sets Date
Date=$(date +%F)

#rsunt selected files
rsync -a --delete --quiet $Source "$Backup/$Date"

#Creats most resent backup date file
echo "$Date" > "$Backup/Date.txt"

#cuts the end off $source
End=$(echo "$Source" | awk -F/ '{print $NF}')

#Checks if Backup is sucsesful
diff -r "$Source" "$Backup/$Date/$End"

#Notifation
if [[ $(echo $?) -eq 0 ]]; then
  message="Success"
else
  message="@everyone Fail"
fi

## format to parse to curl
## echo Sending message: $message
msg_content=\"$message\"

## discord webhook
url='Discord web hook'
curl -H "Content-Type: application/json" -X POST -d "{\"content\": $msg_content}" $url
